### PR TITLE
improve download and run script commands

### PR DESCRIPTION
**Pull request by enoch85**
we can now run all file types \o/

### CODE REVIEW

**Comment by enoch85** [comment]
@morph027 Don't merge, I'll change some more in the other scripts

**Comment by enoch85** [comment]
**READY TO MERGE TO NEXTCLOUD MASTER**
- [ ] lib.sh
- [x] nextcloud-startup-script.sh
- [ ] nextcloud_update.sh
- [X] adduser.sh
- [X] calendar.sh
- [X] change-ncadmin-profile.sh
- [X] change-root-profile.sh
- [x] change_mysql_pass.sh
- [ ] collabora.sh
- [X] contacts.sh
- [X] history.sh
- [X] instruction.sh
- [X] ip.sh
- [X] ip2.sh
- [ ] nextant.sh
- [X] nextcloud.sh
- [X] ntpdate.sh
- [ ] passman.sh
- [ ] phpmyadmin_install_ubuntu16.sh
- [X] recover_apps.py
- [ ] redis-server-ubuntu16.sh
- [ ] security.sh
- [X] setup_secure_permissions_nextcloud.sh
- [ ] spreedme.sh
- [X] temporary-fix.sh
- [X] test_connection.sh
- [X] trusted.sh
- [X] update-config.php
- [x] webmin.sh
- [ ] activate-ssl.sh
- [ ] test-new-config.sh

**CLEAN UP LEFT**
- [x] remove all `sleep` before a script is run (takes a while to load the bash anyway so no sleep is needed)
- [ @morph027 ] while loop when asking if the domain is correct in activate-ssl.sh
- [x] change name of the function `install_3rdparty_app` --> `run_static_script`
- [X] create functions for php scripts as well `run_php_script` & `download_static_php_script` (or can we change the current function to run/download any script no matter the type (.sh|.php))?
- [X] https://github.com/enoch85/vm/blob/patch-1/static/nextant.sh#L116 (Nextant)
- [X] Fix the failing install_3rdparty_app function (I don't think it's the function but something fails anyway)
- [ @morph027 ] Adding spinner_loading for each time the lib.sh is imported (it takes a while and the marker just blinks)
- [X] https://github.com/enoch85/vm/blob/patch-1/nextcloud-startup-script.sh#L281 & https://github.com/enoch85/vm/blob/patch-1/nextcloud-startup-script.sh#L283(test mysql)
- [ @morph027 ] Fix the colors here: https://github.com/enoch85/vm/blob/patch-1/nextcloud-startup-script.sh#L456
- [ @morph027 ] Unset all api calls to Github in lib.sh and only use them where it's needed to avoid being banned (https://developer.github.com/v3/#abuse-rate-limits) or use some kind of function to avoid this. Btw, maybe rawgist will fix this, because it's sending the correct headers?
- [x] remove unnecessary / after the `$NCREPO` for download
- [x] sed all the `bash $SCRIPTS/setup_secure_permissions.sh` to `$SECURE`
- [ ] use spinner_loading in .bash_profile (?) REASON: to be able to use spinner_loading when loading the script at first boot (it takes a while)
- [ ] Final tests
- [ @morph027 ] Squash all commits into one single commit before merge (too many commits, would be nice with one big commit instead) :)
- [ ] Celebrate and donate! :D

**Comment by enoch85** [comment]
@morph027 Can you merge this so I can test? Thanks!

**Comment by enoch85** [comment]
**DON'T MERGE** WIll fix some minor issues

**Comment by enoch85** [comment]
Tested LE script and it generates a SSL cert, but keeps trying even if the cert is it succeeded. Can you have a look @morph027 ?

``` 
    # Check if $CERTFILES exists
    if [ -d "$CERTFILES" ]
    then
        # Generate DHparams chifer
        if [ ! -f "$DHPARAMS" ]
        then
            openssl dhparam -dsaparam -out "$DHPARAMS" 8192
        fi
        # Activate new config
        check_command bash "$SCRIPTS/test-new-config.sh" "$domain.conf"
    else
        printf "${ICyan}It seems like no certs were generated, we do %s more tries.${Color_Off}" "$((NR_OF_ATTEMPTS-ATTEMPT))"
        any_key "Press any key to continue..."
        ((ATTEMPT++))

    fi
done
```

**Comment by enoch85** [comment]
Ignore the error, it should be like that otherwise the user gets the date when installing SSL and not the date of the log entry.

**Comment by enoch85** [comment]
**READY TO MERGE**

Now you have the last remaining issues to fix @morph027 :)

**Comment by enoch85** [comment]
@morph027 Can you merge please?

**Comment by enoch85** [comment]
@morph027 I want to merge everything to Nextcloud master tomorrow. Can you please have a a look at the remaining issues? Thanks!

This can be merged btw, I don't know how to fix the LE ATTEMTS issue nor the spinner loading when lib.sh is loaded.

**Comment by morph027** [comment]
Will try to have a look at it ... been busy the last couple of days (release upcoming at work ;) )

**Comment by enoch85** [comment]
@morph027 I totally understand. *Please* try to make it anyway. :)

As you can see those are the only issues left here. I made a new branch in Nextcloud master called ["rewrite"](https://github.com/nextcloud/vm/tree/rewrite). **Squash** all commits into one single commit and push to that branch please. 

I want to be concentrated on work next week, not this. :)

**Pull request merged**
