### PR TITLE
get the latest letsencrypt packages

### PR DESCRIPTION
**Pull request by enoch85**

### CODE REVIEW

**Comment by enoch85** [comment]
Nope, not in this case... :/

**Comment by enoch85** [comment]
Oh, this was to master... nvm, only 2 commits.

**Comment by morph027** [comment]
Will cherry-pick 'em...

**Comment by enoch85** [comment]
Nice!

**Comment by enoch85** [comment]
btw @morph027 how many scripts are left with Shellcheck?

After that we can start improving the code in general

**Comment by morph027** [comment]
https://github.com/nextcloud/vm/issues/20#issuecomment-289994848

**Pull request merged**
