### PR TITLE
Introduce a new function - SPINNER! :D

### PR DESCRIPTION
**Pull request by enoch85**
Use this where it takes time to load so that the user can see that something is happening in the background instead of thinking that it halted or something.

### CODE REVIEW

**Comment by enoch85** [comment]
@morph027 Can you introduce this on the other scripts as well? For now we use it when `apt update -q2` 

When we polish the scripts we will notice other places where it takes time as well.

**Comment by morph027** [comment]
Ah, yes, good idea...probably wrap this with the ability to check return codes and have one defined function to bail out on errors ....

something like:

```
run_command() {
  eval "$@" & spinner_loading
  if [ ! $? -eq 0 ]; then
    local PARENT_COMMAND
    PARENT_COMMAND="$(ps -o comm= $PPID)"
    echo "command \"$*\" in \"$PARENT_COMMAND\" failed"
    exit 1
  fi
}

run_command "foo"

run_command "bar"
```

**Comment by enoch85** [comment]
Very neat! Sure, let's do it!

**Comment by enoch85** [comment]
Can you change accordingly?

**Comment by morph027** [comment]
Jip...still thinking about a nice way to load some kind of default library containing all our functions just in case we need one. Did something with network load-/sourceable scripts [here](https://gitlab.com/morph027/gitlab-ci-helpers)

Also have a nifty function which checks if a function is defined..which we can use to load a function if we need it:

```
checklib() {
  if [[ $(declare -F $1 &>/dev/null) -eq 0 ]]; then
    eval $@
  else
    return 1
  fi
}

checklib "foo" || . <(curl -sL ... )
```

**Comment by enoch85** [comment]
I'm not folling 100% here, but it defently sounds nice. 

One thing that I wanted to to for a loong time (but didn't figured out how, or spent time on it) is to store all variables that are the same in a separate file, and call them somehow. Take /var/scripts for example... if we want to change that path we need to change it in ALL the scripts. Would be much better and quicker if we could store tha in one file, update it there and then all the variables would listen to that "master variable".

Making sense?

**Comment by morph027** [comment]
Jip, exactly this...same for functions...we do not need 3 times ```ask_yes_or_no``` or whatever else we're using. Same for vars....should be inside on global file, which all scripts are using.

**Comment by enoch85** [comment]
Wow, great! That would also set a standard for variables. Like it is now, some are different than others, not optimal.

Would be super awesome if you could fix it.

**Comment by morph027** [comment]
Will compile a list of functions and vars ... trying to squash them all ;)

**Comment by enoch85** [comment]
Great! I was thinking I will work on the if arguments and remove things like > 0 then.

**Comment by enoch85** [comment]
@morph027 Let's clean up this PR and merge the whole increase-code-quality into morph027/master.

**Comment by enoch85** [comment]
@morph027 Also, can you please open an issue so that we can have a checklist for what's left to do. Thanks!

**Comment by morph027** [comment]
Will do!

**Pull request merged**
